# Generated by Django 5.2.1 on 2025-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('image', models.ImageField(blank=True, upload_to='subject_images/')),
            ],
        ),
    ]
