# Generated by Django 5.2.1 on 2025-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_subject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='file',
        ),
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
