# Generated by Django 5.2.1 on 2025-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_subject_file_remove_subject_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7')], default=0),
            preserve_default=False,
        ),
    ]
