# Generated by Django 5.2.1 on 2025-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectfile',
            name='name',
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='category',
            field=models.CharField(choices=[('notes', 'Chapter Notes'), ('question', 'Previous Year Questions'), ('suggestion', 'Suggestions'), ('syllabus', 'Syllabus'), ('others', 'Others')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectfile',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
