# Generated by Django 5.2.1 on 2025-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_subjectfile_name_subjectfile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='category',
            field=models.CharField(choices=[('chapter_notes', 'Chapter Notes'), ('suggestions', 'Suggestions'), ('previous_questions', 'Previous Questions'), ('syllabus', 'Syllabus')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
