# Generated by Django 5.2.1 on 2025-07-09 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_subject_code_subject_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester', 'title']},
        ),
        migrations.AlterModelOptions(
            name='subjectfile',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')]),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='category',
            field=models.CharField(choices=[('notes', '📘 Chapter Notes'), ('question', '📄 Previous Year Questions'), ('suggestion', '📑 Suggestions'), ('syllabus', '📚 Syllabus'), ('others', '🧾 Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectfile',
            name='file',
            field=models.FileField(upload_to='subject_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip'])]),
        ),
    ]
