# Generated by Django 5.2.1 on 2025-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_subject_options_alter_subjectfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='category',
            field=models.CharField(choices=[('notes', '📘 Chapter Notes'), ('question', '📄 Previous Year Questions'), ('suggestion', '📑 Suggestions'), ('syllabus', '📚 Syllabus'), ('Book', '🧾 Book')], max_length=20),
        ),
    ]
