# Generated by Django 5.2.1 on 2025-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_notice_syllabus_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional: Upload an image or document (PDF, JPG, PNG)', null=True, upload_to='notices/'),
        ),
    ]
