# Generated by Django 5.2.1 on 2025-07-10 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_notice_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
